FROM python:alpine

RUN apk add --no-cache ca-certificates

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
